project:
  type: book
  output-dir: _book
  resources:
    - "assets/**/*.png"

book:
  title: "Life with R"
  description: "Rを始めて使う方への入門書"
  author: 
    - name: 阿部洋輔
      affiliation: 某シンクタンク
      url: https://yo5uke.com/
  date: 2025-02-05
  date-format: "YYYY年M月D日"
  google-analytics: "G-KN42DSQ0YN"
  favicon: assets/icons/abe-r.png
  site-url: https://yo5uke.com/life-with-r
  sharing: [twitter, facebook, linkedin]
  repo-url: https://github.com/yo5uke/life-with-r
  issue-url: https://github.com/yo5uke/life-with-r/issues
  repo-actions: [edit, issue]
  chapters:
    - index.qmd

    - part: "第1部：セットアップ"
      chapters:
        - install.qmd
        - common.qmd
        - try_rstudio.qmd
        - try_positron.qmd
        - start_project.qmd

    - part: "第2部：データ分析の基礎"
      chapters:
        - data_io.qmd
        - data_wrangling_basic.qmd
        - data_wrangling_advanced.qmd
        - visualization_basic.qmd
        - visualization_advanced.qmd
        
  page-footer:
    background: "#f8f9fa"
    center: |
      © 2025-2026 Life with R
    right: |
      このページは[Quarto](https://quarto.org)で作成されました。

execute: 
  freeze: auto
  warning: false

format:
  html:
    theme: 
      - sandstone
    toc: true
    fig-align: center
    link-external-newwindow: true
